name: Hello World
on: workflow_dispatch
   jobs:
     build:
       runs-on: Ubunto_latest
         steps: 
           - name: Build Step
               run: echo "A demo build"
  test: 
     runs-on: Ubunto_latest
        steps:
          - name: Test phase
              run: echo "Running Test cases"

  deploy:
   runs-on: Ubunto_latest
       steps: 
       - name: deploy the app
            run: echo "Deploying the app"
